# forum-service : dev
spring:
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9090
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://202.178.125.77:5401/postgres
    username: admin
    password: Code@Advisors2024
  

logging:
  level:
    root: INFO
    org.springframework.security: debug

server:
  port: 8081
