spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db-edit-profile

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://167.172.78.79:8761/eureka/

server:
  port: 8085