spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://identity.code-advisors.istad.co
  data:
    mongodb:
      uri: mongodb://202.178.125.77:5403/user-service
  kafka:
    security:
      protocol: SSL
    ssl:
      trust-store-location: file:/app/kafka.server.truststore.jks
      trust-store-password: password123
      key-store-location: file:/app/kafka.server.keystore.jks
      key-store-password: password123
      key-password: password123
    producer:
      bootstrap-servers:
        - 34.143.151.53:29093
        - 34.143.151.53:39093
        - 34.143.151.53:49093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers:
        - 34.143.151.53:29093
        - 34.143.151.53:39093
        - 34.143.151.53:49093
      group-id: user-service
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: istad.codeadvisor.userservice.config.kafka.BaseProducerDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
##        spring.json.value.default.type: istad.codeadvisor.userservice.config.kafka.producer.ContentProducer
        spring.json.value.default.type: istad.codeadvisor.userservice.config.kafka.producer.BaseProducer
#handle file size
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 5MB
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://202.178.125.77:1761/eureka/

server:
  port: 8085
