
spring:
  application:
    name: comunnity-engagement-service
  data:
    mongodb:
      uri: mongodb://admin:Code%40Advisors2024@202.178.125.77:5403/
      authentication-database: admin
      database: community-engagement
  kafka:
    bootstrap-servers:
    - 167.172.78.79:9092
    - 167.172.78.79:9093
    - 167.172.78.79:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    stream:
      bindings:
        engagementProcessor-in-0:
          destination: community-engagment
          content-type: application/json
        engagmentProcessor-out-0:
          destination: processed-community-engagment
          content-type: application/json
eureka:
  client:
    service-url:
      defaultZone: http://167.172.78.79:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8086
