spring:
  application:
    name: comunnity-engagement-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://identity.code-advisors.istad.co
  data:
    mongodb:
      # uri: mongodb://localhost:27017/content-service
      uri: mongodb://202.178.125.77:5403/community-engagement
      #uri: mongodb://admin:Code%40Advisors2024@202.178.125.77:5403/
      #authentication-database: admin
      #database: community-engagement
  kafka:
    security:
      protocol: SSL
    ssl:
      trust-store-location: file:/app/kafka.server.truststore.jks
      trust-store-password: password123
      key-store-location: file:/app/kafka.server.keystore.jks
      key-store-password: password123
      key-password: password123
    bootstrap-servers:
      - 34.143.151.53:29093
      - 34.143.151.53:39093
      - 34.143.151.53:49093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    stream:
      bindings:
        engagementProcessor-in-0:
          destination: community-engagment
          content-type: application/json
        engagmentProcessor-out-0:
          destination: processed-community-engagment
          content-type: application/json
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://202.178.125.77:1761/eureka/

server:
  port: 8086
