server:
  port: 8168
  forward-headers-strategy: framework

spring:
  security:
    oauth2:
      client:
        provider:
          code-advisor:
            issuer-uri: https://identity.code-advisors.istad.co
        registration:
          # Register CodeAdvisor Service
          code-advisor:
            provider: code-advisor
            client-id: code-advisor
            client-secret: qwerqwer
            authorization-grant-type:
              - authorization_code
            scope: openid, profile, email, ADMIN, USER
            redirect-uri: https://code-advisors.istad.co/login/oauth2/code/code-advisor
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers
        - SaveSession
      routes:
        - id: identity # Register Identity Service
          uri: lb://identity-service
          predicates:
            - Path=/identity/**
          filters:
            - TokenRelay=
            - RewritePath=/identity/(?<segment>.*),/$\{segment}

        - id: content-service # Register Frontend (NextJS)
          uri: lb://content-service
          predicates:
            - Path=/contents/**
          filters:
            - TokenRelay=
            - RewritePath=/contents/(?<segment>.*),/$\{segment}

        - id: forum-code-advisors
          uri: http://code-advisors-forum-service:8081
          predicates:
            - Path=/forums/**
          filters:
            - TokenRelay=
            - RewritePath=/forums/(?<segment>.*),/$\{segment}

        - id: user-service
          uri: http://code-advisors-user-service:8085
          predicates:
            - Path=/users/**
          filters:
            - TokenRelay=
            - RewritePath=/users/(?<segment>.*),/$\{segment}

        - id: media-service
          uri: http://167.172.78.79:8090
          predicates:
            - Path=/media/**
          filters:
            - TokenRelay=
            - RewritePath=/users/(?<segment>.*),/$\{segment}

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
          filters:
            - TokenRelay=
            - RewritePath=/notifications/(?<segment>.*),/$\{segment}

        - id: community-engagement-service
          uri: lb://community-engagement-service
          predicates:
            - Path=/ces/**
          filters:
            - TokenRelay=
            - RewritePath=/ces/(?<segment>.*),/$\{segment}

        - id: codeAdvisor-ui # Register Frontend (NextJS)
          uri: http://code-advisors-ui:3000
          predicates:
            - Path=/**
          filters:
            - TokenRelay=


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://code-advisors-eureka-server:8761/eureka/

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
