server:
  port: 8168
  forward-headers-strategy: framework
      
spring:
  # security:
  #   oauth2:
  #     client:
  #       provider:
  #         nextjs:
  #           issuer-uri: https://khotixs-auth.devkh.asia
  #           authorization-uri: https://khotixs-auth.devkh.asia/oauth2/authorize
  #           token-uri: https://khotixs-auth.devkh.asia/oauth2/token
  #       #            user-info-uri: ${USER_INFO_URI}

  #       registration:
  #         nextjs:
  #           provider: nextjs
  #           client-id: nextjs
  #           client-secret: nextjs123
  #           authorization-grant-type:
  #             - authorization_code
  #           scope:
  #             - openid
  #             - profile
  #             - email
  #           redirect-uri: https://code-advisors.istad.co/login/oauth2/code/nextjs
  #           client-authentication-method:
  #             - client_secret_post
  #             - client_secret_basic
  security:
    oauth2:
      client:
        provider:
          code-advisor:
            issuer-uri: https://identity.code-advisors.istad.co
            authorization-uri: https://identity.code-advisors.istad.co/oauth2/authorize
            token-uri: https://identity.code-advisors.istad.co/oauth2/token
        registration:
          # Register CodeAdvisor Service
          code-advisor:
            provider: code-advisor
            client-id: code-advisor
            client-secret: qwerqwer
            authorization-grant-type:
              - authorization_code
            scope: openid, profile, email, ADMIN, USER
            redirect-uri: https://code-advisors.istad.co/login/oauth2/code/code-advisor
            client-authentication-method:
              - client_secret_post
              - client_secret_basic
  cloud:
    gateway:
      # globalcors:
      #   corsConfigurations:
      #     '[/**]':
      #       allowedOrigins: "https://code-advisors.istad.co"
      #       allowedMethods:
      #         - GET
      #         - POST
      #         - PUT
      #         - DELETE
      #       allowedHeaders: "*"
      #       allowCredentials: true
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers
        # - DedupeResponseHeader=Set-Cookie
        - SaveSession
      routes:
        - id: identity # Register Identity Service
          uri: lb://identity-service
          # uri: http://35.225.212.218:8086
          predicates:
            - Path=/identity/**
          filters:
            - TokenRelay=
            - RewritePath=/identity/(?<segment>.*),/$\{segment}

        - id: content-service # Register Frontend (NextJS)
          uri: http://code-advisors-content-service:8082
          predicates:
            - Path=/contents/**
          filters:
            - TokenRelay=
            - RewritePath=/contents/(?<segment>.*),/$\{segment}

        - id: forum-code-advisors
          uri: http://code-advisors-forum-service:8081
          predicates:
            - Path=/forums/**
          filters:
            - TokenRelay=
            - RewritePath=/forums/(?<segment>.*),/$\{segment}

        - id: user-service
          uri: http://code-advisors-user-profile-service:8085
          predicates:
            - Path=/users/**
          filters:
            - TokenRelay=
            - RewritePath=/users/(?<segment>.*),/$\{segment}

        - id: media-service
          uri: http://code-advisors-media-service:8090
          predicates:
            - Path=/media/**
          filters:
            - TokenRelay=
            - RewritePath=/users/(?<segment>.*),/$\{segment}

        - id: notification-service
          uri: http://code-advisors-notification-service:8084
          predicates:
            - Path=/notifications/**
          filters:
            - TokenRelay=
            - RewritePath=/notifications/(?<segment>.*),/$\{segment}

        - id: community-engagement-service
          uri: http://code-advisors-ces-service:8086
          predicates:
            - Path=/ces/**
          filters:
            - TokenRelay=
            - RewritePath=/ces/(?<segment>.*),/$\{segment}

        - id: codeAdvisor-ui # Register Frontend (NextJS)
          uri: http://code-advisors-ui:3000
          predicates:
            - Path=/**
          filters:
            - TokenRelay=


eureka:
  # instance:
  #   preferIpAddress: true
  client:
    # fetchRegistry: true
    # registerWithEureka: true
    serviceUrl:
      defaultZone: http://code-advisors-eureka-server:8761/eureka/

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
