server:
  port: 8168

# spring:
#   security:
#     oauth2:
#       client:
#         provider:
# #          google:
# #            authorization-uri: https://accounts.google.com/o/oauth2/auth
# #            token-uri: https://accounts.google.com/o/oauth2/token
# #            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
# #            user-name-attribute: sub
#           code-advisor:
#             issuer-uri: http://127.0.0.1:9090
#             # authorization-uri: http://127.0.0.1:9090/oauth2/authorize
#             # token-uri: http://127.0.0.1:9090/oauth2/token
#         registration:
# #           Register google Service
# #          google:
# #            provider: google
# #            client-id: 897037474382-1eipe3mffu6ielod7kma05fbc1h3siic.apps.googleusercontent.com
# #            client-secret: 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
# #            authorization-grant-type:
# #              - authorization_code
# #            scope: openid, profile, email
# #            redirect-uri: http://localhost:8168/
# #            client-authentication-method: client_secret_post

#           # Register CodeAdvisor Service
#           code-advisor:
#             provider: code-advisor
#             client-id: code-advisor
#             client-secret: qwerqwer
#             authorization-grant-type:
#               - authorization_code
#             scope: openid, profile, email
#             redirect-uri: http://127.0.0.1:8168/login/oauth2/code/code-advisor
spring:
  security:
    oauth2:
      client:
        provider:
          code-advisor:
            issuer-uri: http://127.0.0.1:9090 #https://identity.code-advisors.istad.co  # 
            # authorization-uri: https://identity.code-advisors.istad.co/oauth2/authorize
            # token-uri: https://identity.code-advisors.istad.co/oauth2/token
            authorization-uri: http://127.0.0.1:9090/oauth2/authorize
            token-uri: http://127.0.0.1:9090/oauth2/token
        registration:
          # Register CodeAdvisor Service
          code-advisor:
            provider: code-advisor
            client-id: code-advisor
            client-secret: qwerqwer
            authorization-grant-type:
              - authorization_code
            scope: openid, profile, email, ADMIN, USER
            redirect-uri: http://127.0.0.1:8168/login/oauth2/code/code-advisor #https://code-advisors.istad.co/login/oauth2/code/code-advisor  
            client-authentication-method:
              - client_secret_post
              - client_secret_basic
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers
        - SaveSession
      routes:
        - id: identity # Register Identity Service
          uri: http://127.0.0.1:9090
          predicates:
            - Path=/identity/**
          filters:
            - TokenRelay=
            - RewritePath=/identity/(?<segment>.*),/$\{segment}
            
        - id: notification-service
          uri: http://127.0.0.1:8084
          predicates:
            - Path=/notifications/**
          filters:
            - TokenRelay=
            - RewritePath=/notifications/(?<segment>.*),/$\{segment}

        - id: community-engagement-service
          uri: http://127.0.0.1:8086
          predicates:
            - Path=/ces/**
          filters:
            - TokenRelay=
            - RewritePath=/ces/(?<segment>.*),/$\{segment}

        - id: content-service # Register Frontend (NextJS)
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/contents/**
          filters:
            - TokenRelay=
            - RewritePath=/contents/(?<segment>.*),/$\{segment}

        - id: forum-code-advisors
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/forums/**
          filters:
            - TokenRelay=
            - RewritePath=/forums/(?<segment>.*),/$\{segment}
        # - id: forum-code-advisors
        #   uri: http://127.0.0.1:1081
        #   predicates:
        #     - Path=/forums/**
        #   filters:
        #     - TokenRelay=
        #     - RewritePath=/forums/(?<segment>.*),/$\{segment}

        - id: user-service
          uri: http://127.0.0.1:8085
          predicates:
            - Path=/users/**
          filters:
            - TokenRelay=
            - RewritePath=/users/(?<segment>.*),/$\{segment}

        - id: media-service
          uri: http://167.172.78.79/:8090
          predicates:
            - Path=/media/**
          filters:
            - TokenRelay=
            - RewritePath=/users/(?<segment>.*),/$\{segment}

        - id: codeAdvisor-ui # Register Frontend (NextJS)
          uri: http://127.0.0.1:3000
          predicates:
            - Path=/**
          filters:
            - TokenRelay=

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
