spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://admin:Code%40Advisors2024@202.178.125.77:27017/db-notification?authSource=admin
  kafka:
    bootstrap-servers:
      - 202.178.125.77:29093
      - 202.178.125.77:39093
      - 202.178.125.77:49093
      
    security:
      protocol: SSL
    ssl:
      trust-store-location: classpath:kafka.server.truststore.jks
      trust-store-password: password123
      key-store-location: classpath:kafka.server.keystore.jks
      key-store-password: password123
      key-password: password123

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    #   properties:
    #     spring:
    #       deserializer:
    #         key:
    #           delegate: org.apache.kafka.common.serialization.StringDeserializer
    #         value:
    #           delegate: io.confluent.kafka.serializers.KafkaAvroDeserializer

    # properties:
    #   schema:
    #     registry:
    #       url: http://206.189.159.20:8998
    #       request:
    #         timeout:
    #           ms: 5000
    #       connection:
    #         timeout:
    #           ms: 5000
    #   specific:
    #     avro:
    #       reader: true

    listener:
      missing-topics-fatal: false

  cloud:
    stream:
      bindings:
        notificationProcessor-in-0:
          destination: notifications
          content-type: application/json
        notificationProcessor-out-0:
          destination: processed-notifications
          content-type: application/json
eureka:
  client:
    service-url:
      defaultZone: http://167.172.78.79:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8084
