server:
  port: 8090

minio:
  server:
    url: http://167.172.78.79:27018
    access-key: minioadmin
    secret-key: minioadmin123
    bucket-name: files

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://202.178.125.77:5401/assets
    username: admin
    password: Code@Advisors2024
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

media:
  url: https://media.panda.engineer/api/v1/files/preview

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://167.172.78.79:8761/eureka/
