server:
  port: 8090

minio:
  server:
    url: http://localhost:27018
    access-key: minioadmin
    secret-key: minioadmin123
    bucket-name: files

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/assets
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

media:
  url: http://localhost:8090/api/v1/files/preview