spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://identity.code-advisors.istad.co #http://202.178.125.77:9090
      client:
        registration:
          google:
            client-id: 702679122858-vjsaia60jt9t5thiug8rqpv1rup2f1i9.apps.googleusercontent.com
            client-secret: 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
          github:
            client-id: Iv23lipMLL5PQnt5TVEg
            client-secret: efe4925156f095775fcb8ccc4f9dfaa199caa22d
  kafka:
    bootstrap-servers:
      - 167.172.78.79:29093
      - 167.172.78.79:39093
      - 167.172.78.79:49093   
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
    consumer:
      group-id: user-service
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: co.istad.identityservice.config.kafka.eventClass.UpdateUserEvent
    security:
      protocol: SSL
    ssl:
      trust-store-location: file:/app/kafka.server.truststore.jks
      trust-store-password: password123
      key-store-location: file:/app/kafka.server.keystore.jks
      key-store-password: password123
      key-password: password123
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://202.178.125.77:5402/oauth2
    username: oauth2
    password: Code@Advisors2024
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: istad.codeadvisors@gmail.com
    password: urfl rzjr zbcn jsvn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9090

logging:
  level:
    org:
      springframework:
        #        web: DEBUG
        #        mail: DEBUG
        security: DEBUG
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://202.178.125.77:1761/eureka/


code-advisors:
  ip: 202.178.125.77
  port: 1168
